import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  

      <h1>Imi trebuie rau de tot sa-mi fac treaba cu pizda de Veronica-Futiver!</h1>  
      
    </div>
  )
}
